import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { JugaadResult, SuccessLog } from '../types.ts';
import {
  Search, Route, Sparkles, RefreshCw, AlertTriangle, Coins,
  Navigation, Users, Copy, Check, Share2, Download,
  Train, MapPin, Armchair, Clock, Gauge, Shield,
} from 'lucide-react';
import StationSearch from './StationSearch.tsx';
import { JugaadResultSkeleton } from './Skeleton.tsx';
import { useToast } from './Toast.tsx';

const RECENT_SUCCESS_LOGS: SuccessLog[] = [
  { id: "1", user: "Rahul M.", route: "ADI → NDLS via JP", time: "Just now" },
  { id: "2", user: "Sneha K.", route: "NDLS → BCT via BRC", time: "5m ago" },
  { id: "3", user: "Amit S.", route: "MAS → SBC via JTJ", time: "12m ago" },
  { id: "4", user: "Priya V.", route: "PNBE → NDLS via DDU", time: "19m ago" }
];

// ─── Helper: Build shareable journey text ────────────────────────────────────
function buildJourneyText(result: JugaadResult): string {
  const lines = [
    `🚆 ConfirmHoga AI — Jugaad Route`,
    `━━━━━━━━━━━━━━━━━━━━━━━━`,
    `Train: ${result.trainName} (${result.trainNumber})`,
    `Duration: ${result.totalDuration} | Success Rate: ${result.successRate}%`,
    ``,
    `📍 Route Segments:`,
  ];
  result.segments.forEach((seg, i) => {
    lines.push(`  ${i + 1}. ${seg.from} → ${seg.to} | ${seg.trainName} (${seg.trainNumber})`);
    lines.push(`     Class: ${seg.classType} | ${seg.coach}/Seat ${seg.seat} | ${seg.statusLabel}`);
  });
  lines.push(``);
  lines.push(`💡 AI Strategy: ${result.aiStrategy}`);
  lines.push(`💰 ${result.savings}`);
  if (result.warnings.length) {
    lines.push(``);
    lines.push(`⚠️ Warnings:`);
    result.warnings.forEach(w => lines.push(`  • ${w}`));
  }
  lines.push(`\n— Generated by ConfirmHoga AI`);
  return lines.join('\n');
}

// ─── Helper: Generate PDF from journey ───────────────────────────────────────
function downloadJourneyPdf(result: JugaadResult) {
  // Build an HTML document for print-to-PDF
  const segHtml = result.segments.map((seg, i) => `
    <div style="margin-bottom:16px;padding:12px;border:1px solid #e5e7eb;border-radius:8px;">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
        <strong style="font-size:16px;">Segment ${i + 1}: ${seg.from} → ${seg.to}</strong>
        <span style="padding:2px 10px;border-radius:20px;font-size:12px;background:${seg.status === 'Confirmed' ? '#d1fae5' : '#fef3c7'};color:${seg.status === 'Confirmed' ? '#065f46' : '#92400e'};">${seg.statusLabel}</span>
      </div>
      <table style="width:100%;font-size:13px;">
        <tr><td style="color:#6b7280;width:100px;">Train</td><td>${seg.trainNumber} — ${seg.trainName}</td></tr>
        <tr><td style="color:#6b7280;">Class</td><td>${seg.classType}</td></tr>
        <tr><td style="color:#6b7280;">Coach / Seat</td><td>${seg.coach} / Seat ${seg.seat}</td></tr>
      </table>
    </div>
  `).join('');

  const warnHtml = result.warnings.map(w => `<li style="margin-bottom:4px;color:#92400e;">${w}</li>`).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>ConfirmHoga Journey — ${result.trainName}</title>
    <style>body{font-family:Inter,system-ui,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;color:#111;}
    h1{font-size:22px;margin-bottom:4px;} h2{font-size:16px;color:#6366f1;margin-top:24px;margin-bottom:12px;}
    .meta{display:flex;gap:24px;margin:12px 0;font-size:13px;color:#6b7280;}
    .meta span{background:#f3f4f6;padding:4px 12px;border-radius:6px;}
    .strategy{background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;padding:16px;margin:16px 0;font-size:13px;line-height:1.6;}
    .footer{margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;text-align:center;}
    </style></head><body>
    <h1>🚆 ${result.trainName} (${result.trainNumber})</h1>
    <div class="meta"><span>⏱ ${result.totalDuration}</span><span>✅ ${result.successRate}% Success Rate</span><span>💰 ${result.savings}</span></div>
    <h2>Route Segments</h2>${segHtml}
    <h2>AI Strategy</h2><div class="strategy">${result.aiStrategy}</div>
    ${result.warnings.length ? `<h2>⚠️ Warnings</h2><ul>${warnHtml}</ul>` : ''}
    <div class="footer">Generated by ConfirmHoga AI — ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
    </body></html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const printWindow = window.open(url, '_blank');
  if (printWindow) {
    printWindow.onload = () => {
      printWindow.print();
      URL.revokeObjectURL(url);
    };
  } else {
    // Fallback: download as HTML
    const a = document.createElement('a');
    a.href = url;
    a.download = `ConfirmHoga_Journey_${result.trainNumber}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }
}

export default function JugaadView() {
  const [source, setSource] = useState('NDLS');
  const [destination, setDestination] = useState('BCT');

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<JugaadResult | null>(null);
  const [logs, setLogs] = useState<SuccessLog[]>(RECENT_SUCCESS_LOGS);
  const [swapRotation, setSwapRotation] = useState(0);
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const resultRef = useRef<HTMLDivElement>(null);
  const { addToast } = useToast();

  // Initialize with ADI -> NDLS default mock to render timeline instantly
  useEffect(() => {
    setResult({
      trainName: "Mumbai Rajdhani",
      trainNumber: "12952",
      totalDuration: "15h 40m",
      successRate: 92,
      segments: [
        { id: "1", from: "NDLS", to: "AGC", trainName: "Shatabdi Express", trainNumber: "12002", classType: "CC", coach: "C4", seat: "23", status: "Confirmed", statusLabel: "Confirmed" },
        { id: "2", from: "AGC", to: "BRC", trainName: "Mumbai Rajdhani", trainNumber: "12952", classType: "3A", coach: "B2", seat: "45", status: "RAC", statusLabel: "RAC 12" },
        { id: "3", from: "BRC", to: "BCT", trainName: "Mumbai Rajdhani", trainNumber: "12952", classType: "3A", coach: "B2", seat: "12", status: "Confirmed", statusLabel: "Confirmed" }
      ],
      aiStrategy: "Direct trains are heavily waitlisted (WL 150+). By splitting at AGC and BRC, you secure a confirmed seat for 70% of the journey and a high-probability RAC for the middle leg. This route is highly recommended since BRC serves as a major quota refresh point for this train, meaning vacant seats are systematically cataloged here.",
      savings: "Saves ₹420 vs Dynamic Premium Pricing",
      warnings: [
        "Requires platform change at Agra Cantt (AGC). Keep 45 mins buffer.",
        "Requires changing seats (Seat 45 to 12) inside coach B2 at Vadodara."
      ]
    });
  }, []);

  const handleSearch = async () => {
    if (!source || !destination) {
      addToast({ type: 'error', title: 'Missing Stations', message: 'Please specify both Source and Destination stations.' });
      return;
    }
    if (source === destination) {
      addToast({ type: 'error', title: 'Invalid Route', message: 'Source and Destination cannot be the same station.' });
      return;
    }
    setError(null);
    setLoading(true);
    setResult(null);

    try {
      const response = await fetch(
        `http://127.0.0.1:8000/api/find-jugaad?source=${source}&destination=${destination}`
      );
      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || "Failed to search Jugaad routes.");
      }
      const data: JugaadResult = await response.json();
      setResult(data);
      addToast({ type: 'success', title: 'Route Found!', message: `${data.segments.length} segments mapped with ${data.successRate}% success rate.` });

      const newLog: SuccessLog = {
        id: String(Date.now()),
        user: "You",
        route: `${source.toUpperCase()} → ${destination.toUpperCase()} optimized`,
        time: "Just now"
      };
      setLogs((prev) => [newLog, ...prev.slice(0, 3)]);

      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 250);
    } catch (e: any) {
      addToast({ type: 'error', title: 'Route Search Failed', message: e.message || "Connection error." });
      setError(e.message || "An error occurred connecting to the Jugaad routing system.");
    } finally {
      setLoading(false);
    }
  };

  const swapStations = () => {
    const temp = source;
    setSource(destination);
    setDestination(temp);
    setSwapRotation((prev) => prev + 180);
  };

  const copyToClipboard = async (text: string, field: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(field);
      addToast({ type: 'success', title: 'Copied!', message: `${field} copied to clipboard.`, duration: 2000 });
      setTimeout(() => setCopiedField(null), 2000);
    } catch {
      addToast({ type: 'error', title: 'Copy Failed', message: 'Could not copy to clipboard.' });
    }
  };

  const shareJourney = async () => {
    if (!result) return;
    const text = buildJourneyText(result);

    if (navigator.share) {
      try {
        await navigator.share({ title: `ConfirmHoga — ${result.trainName}`, text });
        addToast({ type: 'success', title: 'Shared!', message: 'Journey shared successfully.' });
      } catch (err: any) {
        if (err.name !== 'AbortError') {
          await copyToClipboard(text, 'Journey details');
        }
      }
    } else {
      await copyToClipboard(text, 'Journey details');
    }
  };

  const handleDownload = () => {
    if (!result) return;
    downloadJourneyPdf(result);
    addToast({ type: 'info', title: 'Generating PDF', message: 'Your journey will open in a print dialog.' });
  };

  return (
    <div className="flex flex-col gap-10">
      {/* 1. Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="flex flex-col gap-3"
      >
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-neutral-900 border border-white/5 font-mono text-[10px] tracking-wider text-cyan-400 w-fit">
          <Route className="w-3 h-3" />
          MULTI-PERMUTATION ROUTING ENGINE
        </div>
        <h1 className="font-geist text-4xl sm:text-5xl font-extrabold text-neutral-100 tracking-tighter leading-[1.1]">
          Find Split Seats{' '}
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-indigo-400">
            Smartly
          </span>
        </h1>
        <p className="text-neutral-400 font-sans text-base sm:text-lg max-w-2xl leading-relaxed">
          Discover hidden seat availability by utilizing automatic boarding-point splitting. Stay on the same train or utilize optimal connections.
        </p>
      </motion.div>

      {/* 2. Route Search Form */}
      <motion.section
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        className="glass-panel p-5 sm:p-8 rounded-2xl relative overflow-hidden shadow-2xl"
        aria-label="Route search form"
      >
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 to-transparent pointer-events-none" />
        <div className="relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_auto_1fr_auto] gap-4 sm:gap-6 items-end">
            <StationSearch id="jugaad-source" label="Source Station" value={source} onChange={setSource} placeholder="Search source station..." disabledCode={destination} />

            <motion.button
              onClick={swapStations}
              animate={{ rotate: swapRotation }}
              transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
              className="flex items-center justify-center h-12 w-12 rounded-full bg-neutral-900 hover:bg-neutral-800 cursor-pointer transition-colors border border-white/5 self-center mx-auto"
              aria-label="Swap source and destination stations"
              type="button"
            >
              <RefreshCw className="w-4 h-4 text-indigo-400" />
            </motion.button>

            <StationSearch id="jugaad-destination" label="Destination Station" value={destination} onChange={setDestination} placeholder="Search destination station..." disabledCode={source} />

            <button
              onClick={handleSearch}
              disabled={loading}
              className="px-8 py-3.5 bg-gradient-to-r from-indigo-500 to-purple-600 hover:shadow-[0_0_15px_rgba(160,95,207,0.4)] text-white font-mono text-sm font-bold rounded-xl transition-all h-[46px] flex items-center justify-center gap-2 group active:scale-95 duration-150 disabled:opacity-50"
              aria-label="Search for split seat routes"
              type="button"
            >
              {loading ? (
                <><RefreshCw className="w-4 h-4 animate-spin" /> MAPPING...</>
              ) : (
                <><Search className="w-4 h-4 group-hover:scale-110 transition-transform" /> Find Seats</>
              )}
            </button>
          </div>
        </div>
      </motion.section>

      {/* 3. Loading Skeleton */}
      <AnimatePresence mode="wait">
        {loading && <JugaadResultSkeleton />}
      </AnimatePresence>

      {/* 4. Result Dashboard */}
      <AnimatePresence>
        {!loading && result && (
          <motion.div
            ref={resultRef}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.5 }}
            className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8 items-start"
          >
            {/* ─── Left: Journey Timeline ─── */}
            <div className="lg:col-span-8 flex flex-col gap-6">
              {/* Section header with action buttons */}
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                <h2 className="font-geist text-xl sm:text-2xl font-extrabold text-neutral-100 flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-indigo-500/10 border border-indigo-500/15 flex items-center justify-center">
                    <Route className="w-4 h-4 text-indigo-400" />
                  </div>
                  Suggested Route
                </h2>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => copyToClipboard(buildJourneyText(result), 'Journey')}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-neutral-900 border border-white/5 hover:border-indigo-500/20 text-neutral-400 hover:text-neutral-200 font-mono text-[10px] transition-all"
                    type="button"
                    aria-label="Copy journey details to clipboard"
                  >
                    {copiedField === 'Journey' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    COPY
                  </button>
                  <button
                    onClick={shareJourney}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-neutral-900 border border-white/5 hover:border-cyan-500/20 text-neutral-400 hover:text-neutral-200 font-mono text-[10px] transition-all"
                    type="button"
                    aria-label="Share journey"
                  >
                    <Share2 className="w-3 h-3" /> SHARE
                  </button>
                  <button
                    onClick={handleDownload}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-neutral-900 border border-white/5 hover:border-purple-500/20 text-neutral-400 hover:text-neutral-200 font-mono text-[10px] transition-all"
                    type="button"
                    aria-label="Download journey as PDF"
                  >
                    <Download className="w-3 h-3" /> PDF
                  </button>
                </div>
              </div>

              {/* Train info strip */}
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.15 }}
                className="glass-panel rounded-xl p-4 flex flex-wrap items-center gap-4 sm:gap-6"
              >
                <div className="flex items-center gap-2.5">
                  <Train className="w-4 h-4 text-indigo-400" />
                  <div>
                    <span className="font-mono text-[10px] text-neutral-500 uppercase block">Train</span>
                    <span className="font-geist text-sm font-bold text-neutral-100">{result.trainNumber} — {result.trainName}</span>
                  </div>
                </div>
                <div className="h-6 w-px bg-white/5 hidden sm:block" />
                <div className="flex items-center gap-2.5">
                  <Clock className="w-4 h-4 text-cyan-400" />
                  <div>
                    <span className="font-mono text-[10px] text-neutral-500 uppercase block">Duration</span>
                    <span className="font-geist text-sm font-bold text-neutral-100">{result.totalDuration}</span>
                  </div>
                </div>
                <div className="h-6 w-px bg-white/5 hidden sm:block" />
                <div className="flex items-center gap-2.5">
                  <Gauge className="w-4 h-4 text-emerald-400" />
                  <div>
                    <span className="font-mono text-[10px] text-neutral-500 uppercase block">Success</span>
                    <span className="font-geist text-sm font-bold text-emerald-400">{result.successRate}%</span>
                  </div>
                </div>
              </motion.div>

              {/* Timeline Nodes */}
              <div className="relative pl-8 before:content-[''] before:absolute before:left-3 before:top-4 before:bottom-4 before:w-0.5 before:bg-gradient-to-b before:from-indigo-500/30 before:via-cyan-500/20 before:to-indigo-500/30">
                <AnimatePresence mode="popLayout">
                  {result.segments.map((seg, idx) => (
                    <motion.div
                      key={seg.id}
                      initial={{ opacity: 0, x: -15 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ duration: 0.5, delay: 0.3 + idx * 0.18 }}
                      className="relative mb-10 last:mb-0"
                    >
                      {/* Timeline node dot */}
                      <div className={`absolute -left-[37px] top-5 w-4 h-4 rounded-full bg-neutral-950 border-2 z-10 ${
                        idx === 0 ? "border-indigo-400 pulse-dot" : seg.status === 'Confirmed' ? "border-emerald-400" : "border-amber-400"
                      }`} />

                      <div className="glass-panel rounded-xl p-4 sm:p-5 hover:border-indigo-500/20 transition-all group relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-20 h-20 bg-gradient-to-bl from-white/[0.02] to-transparent rounded-bl-full pointer-events-none" />

                        <div className="flex justify-between items-start flex-wrap gap-3 mb-4">
                          <div className="flex items-center gap-3">
                            <div className="flex items-center gap-2">
                              <MapPin className="w-3.5 h-3.5 text-indigo-400" />
                              <span className="font-geist text-lg sm:text-xl font-bold text-neutral-100">{seg.from}</span>
                            </div>
                            <span className="text-neutral-600 font-mono text-xs">→</span>
                            <div className="flex items-center gap-2">
                              <MapPin className="w-3.5 h-3.5 text-cyan-400" />
                              <span className="font-geist text-lg sm:text-xl font-bold text-neutral-100">{seg.to}</span>
                            </div>
                          </div>

                          <span className={`font-mono text-[10px] px-3 py-1 rounded-full border font-bold ${
                            seg.status === 'Confirmed'
                              ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400'
                              : 'bg-amber-500/10 border-amber-500/20 text-amber-400'
                          }`}>
                            {seg.statusLabel}
                          </span>
                        </div>

                        <div className="flex flex-wrap gap-4 sm:gap-5 items-center text-sm">
                          <div className="flex items-center gap-2">
                            <Train className="w-3.5 h-3.5 text-neutral-500" />
                            <div className="flex flex-col">
                              <span className="font-mono text-[9px] text-neutral-600 uppercase">Train</span>
                              <span className="font-bold text-neutral-200 text-xs">{seg.trainNumber}</span>
                            </div>
                          </div>
                          <div className="h-6 w-px bg-white/5 hidden sm:block" />
                          <div className="flex items-center gap-2">
                            <Shield className="w-3.5 h-3.5 text-neutral-500" />
                            <div className="flex flex-col">
                              <span className="font-mono text-[9px] text-neutral-600 uppercase">Class</span>
                              <span className="text-neutral-200 text-xs">{seg.classType}</span>
                            </div>
                          </div>
                          <div className="h-6 w-px bg-white/5 hidden sm:block" />
                          <div className="flex items-center gap-2">
                            <Armchair className="w-3.5 h-3.5 text-indigo-400" />
                            <div className="flex flex-col">
                              <span className="font-mono text-[9px] text-neutral-600 uppercase">Seat</span>
                              <span className="font-bold text-indigo-400 text-xs">{seg.coach} / {seg.seat}</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </div>
            </div>

            {/* ─── Right: AI Strategy + Logs ─── */}
            <aside className="lg:col-span-4 flex flex-col gap-5">
              {/* AI Strategy Panel — enhanced glow */}
              <motion.div
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5 }}
                className="glow-card p-6 sm:p-7 relative overflow-hidden shadow-2xl"
              >
                {/* Ambient glow orbs */}
                <div className="absolute top-0 right-0 w-48 h-48 bg-cyan-400/5 rounded-full blur-[80px] pointer-events-none" />
                <div className="absolute bottom-0 left-0 w-40 h-40 bg-indigo-500/5 rounded-full blur-[60px] pointer-events-none" />
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-32 h-32 bg-purple-500/4 rounded-full blur-[60px] pointer-events-none" />

                {/* Top accent line */}
                <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-cyan-400/30 to-transparent" />

                <div className="relative z-10 flex flex-col gap-6">
                  {/* Header with icon and badge */}
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-500/15 to-indigo-500/15 border border-cyan-500/20 flex items-center justify-center relative">
                        <Sparkles className="w-5 h-5 text-cyan-400" />
                        <div className="absolute inset-0 rounded-xl bg-cyan-400/5 animate-pulse" />
                      </div>
                      <div>
                        <h3 className="font-geist text-lg font-bold text-neutral-100">AI Strategy</h3>
                        <span className="font-mono text-[9px] text-cyan-400/60 uppercase tracking-widest">Neural Route Analysis</span>
                      </div>
                    </div>
                    <div className="px-2.5 py-1 rounded-full bg-cyan-500/8 border border-cyan-500/15 font-mono text-[9px] text-cyan-400 font-bold uppercase tracking-wider flex items-center gap-1.5">
                      <div className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
                      LIVE
                    </div>
                  </div>

                  {/* Strategy text with left accent */}
                  <div className="pl-4 border-l-2 border-cyan-400/20">
                    <p className="text-neutral-300 text-sm leading-relaxed font-sans">
                      {result.aiStrategy}
                    </p>
                  </div>

                  {/* Animated Confidence Meter — enhanced */}
                  <div className="p-5 rounded-xl bg-neutral-900/60 border border-white/5 relative overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-r from-indigo-500/5 via-transparent to-cyan-500/5 pointer-events-none" />
                    <div className="relative z-10">
                      <div className="flex justify-between items-center mb-3 font-mono text-xs">
                        <span className="text-neutral-400 uppercase flex items-center gap-2">
                          <Gauge className="w-3.5 h-3.5 text-cyan-400" />
                          Route Reliability Index
                        </span>
                        <span className="text-cyan-400 font-bold text-base tabular-nums">{result.successRate}%</span>
                      </div>
                      <div className="w-full bg-neutral-950 rounded-full h-3 overflow-hidden">
                        <motion.div
                          className="h-3 rounded-full relative"
                          style={{
                            background: result.successRate >= 80
                              ? 'linear-gradient(90deg, #6366f1, #06b6d4, #34d399)'
                              : result.successRate >= 50
                              ? 'linear-gradient(90deg, #6366f1, #fbbf24)'
                              : 'linear-gradient(90deg, #6366f1, #f43f5e)',
                          }}
                          initial={{ width: 0 }}
                          animate={{ width: `${result.successRate}%` }}
                          transition={{ duration: 1.4, delay: 0.5, ease: [0.16, 1, 0.3, 1] }}
                        >
                          <div className="absolute inset-0 bg-gradient-to-r from-white/0 via-white/20 to-white/0 rounded-full animate-pulse" />
                        </motion.div>
                      </div>
                    </div>
                  </div>

                  {/* Stats cards — improved spacing */}
                  <div className="space-y-3">
                    <motion.div
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.7, duration: 0.4 }}
                      className="flex items-center gap-3 p-3.5 rounded-xl bg-emerald-500/5 border border-emerald-500/15 group hover:bg-emerald-500/8 transition-colors"
                    >
                      <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/15 flex items-center justify-center flex-shrink-0">
                        <Coins className="w-4 h-4 text-emerald-400" />
                      </div>
                      <span className="text-emerald-300 text-sm font-medium">{result.savings}</span>
                    </motion.div>

                    {result.warnings.map((warn, i) => (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.8 + i * 0.12, duration: 0.4 }}
                        className="flex items-start gap-3 p-3.5 rounded-xl bg-amber-500/5 border border-amber-500/15 group hover:bg-amber-500/8 transition-colors"
                      >
                        <div className="w-8 h-8 rounded-lg bg-amber-500/10 border border-amber-500/15 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <AlertTriangle className="w-4 h-4 text-amber-500" />
                        </div>
                        <span className="text-amber-200/80 leading-relaxed text-xs">{warn}</span>
                      </motion.div>
                    ))}
                  </div>

                  {/* CTA button — enhanced glow on hover */}
                  <motion.button
                    whileHover={{ scale: 1.01 }}
                    whileTap={{ scale: 0.98 }}
                    className="w-full py-4 bg-gradient-to-r from-indigo-500 via-purple-500 to-indigo-600 hover:shadow-[0_0_30px_rgba(109,40,217,0.4)] text-white font-mono text-sm font-bold uppercase tracking-wider rounded-xl transition-all flex items-center justify-center gap-2.5"
                    type="button"
                  >
                    <Navigation className="w-4 h-4" />
                    Lock & Book Route
                  </motion.button>
                </div>
              </motion.div>

              {/* Success Ticker */}
              <motion.div
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6 }}
                className="glass-panel p-5 rounded-xl"
              >
                <h4 className="font-geist text-sm font-bold text-neutral-200 flex items-center gap-2 mb-3 border-b border-white/5 pb-3">
                  <Users className="w-4 h-4 text-indigo-400" />
                  Recent Jugaad Success
                </h4>
                <div className="space-y-3">
                  {logs.map((log, idx) => (
                    <motion.div
                      key={log.id}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: 0.7 + idx * 0.08 }}
                      className="flex justify-between items-center py-1 border-b border-white/5 last:border-0"
                    >
                      <div className="flex flex-col">
                        <span className="font-sans text-xs font-bold text-neutral-200">{log.user}</span>
                        <span className="font-mono text-[10px] text-neutral-400 mt-0.5">{log.route}</span>
                      </div>
                      <span className="font-mono text-[10px] text-indigo-400">{log.time}</span>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            </aside>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
