import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { PnrResult } from '../types.ts';
import { Sparkles, Train, HelpCircle, CheckCircle2, AlertTriangle, AlertCircle, RefreshCw } from 'lucide-react';

export default function PnrView() {
  const [pnr, setPnr] = useState('');
  const [days, setDays] = useState('14');
  const [wl, setWl] = useState('45');
  const [festival, setFestival] = useState(false);

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<PnrResult | null>(null);

  // Initialize with a beautiful placeholder to show the gauge immediately
  useEffect(() => {
    setResult({
      pnr: "1234567890",
      probability: 90,
      status: "Safe Zone",
      statusColor: "emerald",
      logic: [
        "Historical trends show high cancellation rates during final 48 hours.",
        "Current waitlist dynamics depict robust depletion velocity (4.2/hr).",
        "Primary General Quota remains below structural saturation boundaries.",
        "Current non-holiday weekend clusters minimize charting pressure."
      ],
      explanation: "Historical trends indicate a high cancellation rate during the final 48 hours before departure. Coupled with the current non-festival season context, the algorithm determines a strong probability of movement from Waitlist 45 to Confirmed. Keep this ticket active."
    });
  }, []);

  const handlePredict = async () => {
    if (!pnr || pnr.length !== 10 || isNaN(Number(pnr))) {
      setError("Please enter a valid 10-digit PNR number.");
      return;
    }
    setError(null);
    setLoading(true);

    try {
      const response = await fetch(
        `http://127.0.0.1:8000/api/predict-pnr?days_left=${days}&current_wl=${wl}&is_festival=${festival ? 1 : 0}`
      );
      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || "Failed to calculate prediction.");
      }
const apiData = await response.json();

setResult({
  pnr,
  probability: parseFloat(apiData.confirmation_probability),
  status: apiData.prediction_status,
  statusColor:
    apiData.prediction_status === "Safe Zone"
      ? "emerald"
      : apiData.prediction_status === "Risky"
      ? "amber"
      : "rose",

  logic: [
    `Days Left: ${apiData.days_left}`,
    `Current Waitlist: ${apiData.current_waitlist}`,
    `Festival Season: ${apiData.is_festival_season}`,
    "Prediction generated by Random Forest ML model."
  ],

  explanation:
    "Prediction received successfully from the FastAPI backend."
});
    } catch (e: any) {
      setError(e.message || "An error occurred connecting to the neural prediction server.");
    } finally {
      setLoading(false);
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "Safe Zone":
        return <CheckCircle2 className="w-5 h-5 text-emerald-400" />;
      case "Moderate Zone":
        return <AlertTriangle className="w-5 h-5 text-amber-400" />;
      default:
        return <AlertCircle className="w-5 h-5 text-rose-500" />;
    }
  };

  const getStatusColorClass = (color: string) => {
    switch (color) {
      case "emerald":
        return {
          bg: "bg-emerald-500/10",
          border: "border-emerald-500/25",
          text: "text-emerald-400"
        };
      case "amber":
        return {
          bg: "bg-amber-500/10",
          border: "border-amber-500/25",
          text: "text-amber-400"
        };
      default:
        return {
          bg: "bg-rose-500/10",
          border: "border-rose-500/25",
          text: "text-rose-400"
        };
    }
  };

  // Determine stroke-dashoffset for circular progress gauge
  const radius = 70;
  const circumference = radius * 2 * Math.PI;
  const progressPercent = result ? result.probability : 0;
  const strokeOffset = circumference - (progressPercent / 100) * circumference;

  return (
    <div className="flex flex-col gap-12">
      {/* 1. Header description */}
      <div className="flex flex-col gap-2">
        <h1 className="font-geist text-5xl font-extrabold text-neutral-100 tracking-tighter">
          Predict Your Journey
        </h1>
        <p className="text-neutral-400 font-sans text-lg max-w-2xl leading-relaxed">
          Access our server-side neural prediction models. We check charting velocities, waitlist cancel logs, and holiday traffic trends to deliver high-precision confirmation rates.
        </p>
      </div>

      {/* 2. Grid Dashboard */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Input Parameters panel */}
        <div className="lg:col-span-5 flex flex-col gap-6">
          <div className="glass-panel p-8 rounded-2xl relative overflow-hidden flex flex-col gap-6">
            <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent"></div>
            
            <h2 className="font-geist text-xl font-bold text-neutral-100 flex items-center gap-2">
              <Train className="w-5 h-5 text-indigo-400" />
              Journey Parameters
            </h2>

            {/* PNR input */}
            <div className="flex flex-col gap-2">
              <label className="font-mono text-xs text-neutral-400 uppercase tracking-widest">
                10-Digit PNR Number
              </label>
              <input 
                value={pnr}
                onChange={(e) => setPnr(e.target.value.replace(/\D/g, '').slice(0, 10))}
                className="w-full bg-neutral-950 border-b border-neutral-500 focus:border-cyan-400 py-2.5 px-1 font-mono text-lg text-neutral-100 focus:outline-none focus:ring-0 transition-all placeholder:text-neutral-700"
                placeholder="e.g. 1234567890"
                type="text"
              />
            </div>

            {/* Grid for Days Left & Current WL */}
            <div className="grid grid-cols-2 gap-6">
              <div className="flex flex-col gap-2">
                <label className="font-mono text-xs text-neutral-400 uppercase tracking-widest">
                  Days Left
                </label>
                <input 
                  value={days}
                  onChange={(e) => setDays(e.target.value.replace(/\D/g, ''))}
                  className="w-full bg-neutral-950 border-b border-neutral-500 focus:border-cyan-400 py-2.5 px-1 font-mono text-lg text-neutral-100 focus:outline-none focus:ring-0 transition-all"
                  type="text"
                  placeholder="14"
                />
              </div>

              <div className="flex flex-col gap-2">
                <label className="font-mono text-xs text-neutral-400 uppercase tracking-widest">
                  WL Position
                </label>
                <input 
                  value={wl}
                  onChange={(e) => setWl(e.target.value.replace(/\D/g, ''))}
                  className="w-full bg-neutral-950 border-b border-neutral-500 focus:border-cyan-400 py-2.5 px-1 font-mono text-lg text-neutral-100 focus:outline-none focus:ring-0 transition-all"
                  type="text"
                  placeholder="45"
                />
              </div>
            </div>

            {/* Festival Season toggle */}
            <div className="flex items-center justify-between p-4 rounded-xl bg-neutral-900 border border-white/5 mt-2">
              <div className="flex flex-col">
                <span className="font-sans text-sm font-bold text-neutral-200">Festival Season / Peak Time</span>
                <span className="font-sans text-xs text-neutral-400">Increases traffic load weights</span>
              </div>
              <label className="relative inline-flex items-center cursor-pointer">
                <input 
                  type="checkbox" 
                  checked={festival}
                  onChange={(e) => setFestival(e.target.checked)}
                  className="sr-only peer" 
                />
                <div className="w-11 h-6 bg-neutral-700 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-neutral-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-indigo-500"></div>
              </label>
            </div>

            {/* Error messaging */}
            {error && (
              <div className="p-3.5 rounded-lg bg-rose-500/10 border border-rose-500/25 text-rose-400 text-xs font-mono">
                {error}
              </div>
            )}

            {/* Action button */}
            <button
              onClick={handlePredict}
              disabled={loading}
              className="w-full py-4 bg-gradient-to-r from-indigo-500 via-purple-500 to-indigo-600 text-white font-mono text-sm font-bold uppercase tracking-wider rounded-lg hover:shadow-[0_0_20px_rgba(109,40,217,0.4)] disabled:opacity-50 transition-all flex justify-center items-center gap-2 group active:scale-95 duration-150 mt-4"
            >
              {loading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin text-white" />
                  CONNECTING_TO_NODES...
                </>
              ) : (
                <>
                  PREDICT MY PNR
                  <RefreshCw className="w-4 h-4 group-hover:rotate-180 transition-transform duration-500" />
                </>
              )}
            </button>
          </div>

          {/* Active node details */}
          <div className="glass-panel p-5 rounded-xl border-l-4 border-l-cyan-400">
            <div className="flex gap-4 items-start">
              <span className="material-symbols-outlined text-cyan-400 mt-0.5">info</span>
              <div>
                <h4 className="font-sans text-sm font-bold text-neutral-100">Deterministic Confidence</h4>
                <p className="font-sans text-xs text-neutral-400 leading-normal mt-1">
                  Predictive calculations incorporate seasonal cancellation coefficients and waitlist volatility index (WVI) updated every 10 minutes.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Prediction Outputs panel */}
        <div className="lg:col-span-7 flex flex-col gap-6">
          <AnimatePresence mode="wait">
            {result && (
              <motion.div
                key={result.pnr + result.probability}
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.5 }}
                className="flex flex-col gap-6"
              >
                {/* Circular Gauge Card */}
                <div className="glass-panel p-10 rounded-2xl relative overflow-hidden bg-gradient-to-br from-indigo-950/10 via-neutral-950 to-neutral-950 flex flex-col items-center justify-center text-center">
                  <div className="absolute top-0 right-0 w-48 h-48 bg-purple-500/5 rounded-full blur-[80px]"></div>
                  
                  <span className="font-mono text-xs text-neutral-400 uppercase tracking-[0.2em] mb-8">
                    Estimated Probability Result
                  </span>

                  {/* SVG Gauge */}
                  <div className="relative flex items-center justify-center">
                    <svg className="w-64 h-64 transform -rotate-90">
                      <circle 
                        className="text-neutral-900" 
                        cx="128" 
                        cy="128" 
                        fill="transparent" 
                        r={radius} 
                        stroke="currentColor" 
                        strokeWidth="8"
                      />
                      <circle 
                        className={`transition-all duration-1000 ${
                          result.status === "Safe Zone" 
                            ? "text-emerald-400" 
                            : result.status === "Moderate Zone" 
                            ? "text-amber-400" 
                            : "text-rose-500"
                        }`}
                        cx="128" 
                        cy="128" 
                        fill="transparent" 
                        r={radius} 
                        stroke="currentColor" 
                        strokeDasharray={circumference}
                        strokeDashoffset={strokeOffset}
                        strokeLinecap="round" 
                        strokeWidth="12"
                      />
                    </svg>
                    <div className="absolute flex flex-col items-center">
                      <span className="font-geist text-5xl font-extrabold text-neutral-100">
                        {result.probability}%
                      </span>
                      <span className="font-mono text-[10px] text-neutral-400 mt-2 uppercase tracking-widest">
                        CONFIRM CHANCE
                      </span>
                    </div>
                  </div>

                  {/* Status Badging */}
                  <div className="mt-8">
                    {(() => {
                      const colorStyles = getStatusColorClass(result.statusColor);
                      return (
                        <div className={`inline-flex items-center gap-2 border px-6 py-2 rounded-full font-mono text-xs font-bold uppercase tracking-wider ${colorStyles.bg} ${colorStyles.border} ${colorStyles.text}`}>
                          {getStatusIcon(result.status)}
                          {result.status}
                        </div>
                      );
                    })()}
                  </div>
                </div>

                {/* AI Reasoning Strategy */}
                <div className="glass-panel p-8 rounded-2xl relative flex flex-col gap-6">
                  <div className="absolute -top-3.5 -left-3.5 bg-indigo-600 text-white w-9 h-9 rounded-full flex items-center justify-center shadow-lg border border-white/10">
                    <Sparkles className="w-4 h-4" />
                  </div>

                  <div className="pl-4">
                    <h3 className="font-mono text-xs text-indigo-300 font-bold uppercase tracking-widest mb-4">
                      Neural Analysis Logic
                    </h3>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                      {result.logic.map((bullet, idx) => (
                        <div key={idx} className="p-4 rounded-lg bg-neutral-900 border border-white/5 flex flex-col gap-1.5">
                          <span className="font-mono text-[10px] text-indigo-400 font-bold uppercase">
                            FACTOR {idx + 1}
                          </span>
                          <p className="font-sans text-xs text-neutral-300 leading-relaxed">
                            {bullet}
                          </p>
                        </div>
                      ))}
                    </div>

                    <p className="font-sans text-sm text-neutral-300 leading-relaxed border-t border-white/5 pt-4">
                      {result.explanation}
                    </p>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
